# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1087, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_channel_label = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_channel_label.sizePolicy().hasHeightForWidth())
        self.widget_channel_label.setSizePolicy(sizePolicy)
        self.widget_channel_label.setObjectName("widget_channel_label")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_channel_label)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_channel_1 = QtWidgets.QLabel(self.widget_channel_label)
        self.label_channel_1.setObjectName("label_channel_1")
        self.verticalLayout_2.addWidget(self.label_channel_1)
        self.label_channel_2 = QtWidgets.QLabel(self.widget_channel_label)
        self.label_channel_2.setObjectName("label_channel_2")
        self.verticalLayout_2.addWidget(self.label_channel_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_channel_label)
        self.widget_channel_waveform = QtWidgets.QWidget(self.widget)
        self.widget_channel_waveform.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_channel_waveform.sizePolicy().hasHeightForWidth())
        self.widget_channel_waveform.setSizePolicy(sizePolicy)
        self.widget_channel_waveform.setObjectName("widget_channel_waveform")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_channel_waveform)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_channel_1 = QtWidgets.QScrollArea(self.widget_channel_waveform)
        self.scrollArea_channel_1.setWidgetResizable(True)
        self.scrollArea_channel_1.setObjectName("scrollArea_channel_1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1053, 246))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_channel_1.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea_channel_1)
        self.scrollArea_channel_2 = QtWidgets.QScrollArea(self.widget_channel_waveform)
        self.scrollArea_channel_2.setWidgetResizable(True)
        self.scrollArea_channel_2.setObjectName("scrollArea_channel_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1053, 245))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_channel_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.addWidget(self.scrollArea_channel_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_channel_waveform)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDSP_function = QtWidgets.QMenu(self.menubar)
        self.menuDSP_function.setObjectName("menuDSP_function")
        self.menuDeep_Learning = QtWidgets.QMenu(self.menuDSP_function)
        self.menuDeep_Learning.setObjectName("menuDeep_Learning")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.button_music_import = QtWidgets.QAction(MainWindow)
        self.button_music_import.setObjectName("button_music_import")
        self.action_Music_Genre_Classification = QtWidgets.QAction(MainWindow)
        self.action_Music_Genre_Classification.setObjectName("action_Music_Genre_Classification")
        self.button_mgc = QtWidgets.QAction(MainWindow)
        self.button_mgc.setObjectName("button_mgc")
        self.actionfff = QtWidgets.QAction(MainWindow)
        self.actionfff.setObjectName("actionfff")
        self.menuFile.addAction(self.button_music_import)
        self.menuDeep_Learning.addAction(self.button_mgc)
        self.menuDSP_function.addAction(self.menuDeep_Learning.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDSP_function.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_channel_1.setText(_translate("MainWindow", "Channel 1"))
        self.label_channel_2.setText(_translate("MainWindow", "Channel 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDSP_function.setTitle(_translate("MainWindow", "Function"))
        self.menuDeep_Learning.setTitle(_translate("MainWindow", "Deep Learning"))
        self.button_music_import.setText(_translate("MainWindow", "Import"))
        self.action_Music_Genre_Classification.setText(_translate("MainWindow", "Music-Genre-Classification"))
        self.button_mgc.setText(_translate("MainWindow", "Music-Genre-Classification"))
        # self.actionfff.setText(_translate("MainWindow", "fff"))

